Development
MDE4CPP/MDE4CPP pull request #23
Opened 2020-02-03 11:17 UTC by HammerMaximilian

**Ergebnisse Projektseminar "PSCS für MDE4CPP" + UML-Standardprofil**

**Überblick Änderungen seit letztem Merge (Dez. 2019):**
- PSCS: Modell + generierte Files
- PSSM: Referenzen zur fUML auf neue fUML-Version (hierarchische Struktur) angepasst
- UML-Standardprofil: Modell + generierter Code, Ecore- sowie UML-Modell
- UML: Modell + generierte Files
- fUML4CPP-Generator: Merge meines Generators mit aktuellerer Version aus dem Basis-Respository
- UML4CPP-Generator: MTL-Files
- Gradle Tasks: Generieren und Kompilieren von PSCS und Standardprofil in "generelle" MDE4CPP-Tasks aufgenommen

2020-02-04 09:03 UTC, AlexanderWichmann requested changes
Hallo, 

bei dem Pull-Request sind zahlreiche Binary-Datei dabei.
Können Sie diese bitte aus dem Pull-Request entfernen?

Das betrifft anderem folgenden Ordner:
- MDE4CPP/generator/UML4CPP/UML4CPP.generator.compiler/build/* 
- MDE4CPP/generator/UML4CPP/UML4CPP.generator/bin/* 
- MDE4CPP/generator/UML4CPP/UML4CPP.generator/build/* 
- MDE4CPP/generator/ecore4CPP/ecore4CPP.generator/bin/* 
- MDE4CPP/generator/ecore4CPP/ecore4CPP.generator/build/* 

Generierte Source-Code Dateien können gerne eingecheckt werden (src_gen-Ordner).
Build- und Binary-Verzeichnisse sollten allerdings nicht im Repository vorhanden sein (bin/build/.cmake).

Vielen Dank und viele Grüße

Alexander Wichmann

2020-02-06 08:31 UTC, HammerMaximilian commented
Hallo,

oh stimmt, das sollte natürlich nicht sein.
Ich bin diese Woche dienstlich im Ausland, ist es okay, wenn ich mir das ganze am Wochenende oder Anfang nächster Woche anschaue?
Bin auch noch nicht so geübt im Umgang mit Github und muss mir erstmal anschauen, wie man Dinge aus einem Pull-Request wieder entfernt.


Viele Grüße
Maximilian Hammer

Von: Alexander Wichmann <notifications@github.com>
Gesendet: Dienstag, 4. Februar 2020 11:03
An: MDE4CPP/MDE4CPP <MDE4CPP@noreply.github.com>
Cc: HammerMaximilian <maximilian.hammer@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [MDE4CPP/MDE4CPP] Development (#23)


@AlexanderWichmann requested changes on this pull request.

Hallo,

bei dem Pull-Request sind zahlreiche Binary-Datei dabei.
Können Sie diese bitte aus dem Pull-Request entfernen?

Das betrifft anderem folgenden Ordner:

  *   MDE4CPP/generator/UML4CPP/UML4CPP.generator.compiler/build/*
  *   MDE4CPP/generator/UML4CPP/UML4CPP.generator/bin/*
  *   MDE4CPP/generator/UML4CPP/UML4CPP.generator/build/*
  *   MDE4CPP/generator/ecore4CPP/ecore4CPP.generator/bin/*
  *   MDE4CPP/generator/ecore4CPP/ecore4CPP.generator/build/*

Generierte Source-Code Dateien können gerne eingecheckt werden (src_gen-Ordner).
Build- und Binary-Verzeichnisse sollten allerdings nicht im Repository vorhanden sein (bin/build/.cmake).

Vielen Dank und viele Grüße

Alexander Wichmann

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MDE4CPP/MDE4CPP/pull/23?email_source=notifications&email_token=AOBXXT37LSCRI5H7R6W2YM3RBEVOBA5CNFSM4KPDMPA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCUDX6DY#pullrequestreview-352812815>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOBXXTZ45LPQR3QGNNNDJSDRBEVOBANCNFSM4KPDMPAQ>.

2020-02-06 08:36 UTC, AlexanderWichmann commented
Klar, bis nächste Woche kann der Spaß noch warten. Kein Problem.

Eine Korrektur von einem Pull-Request habe ich auch noch nicht gemacht. Im Zweifel ist die einfachste Lösung, den hier zu schließen und einen neuen zu erstellen. 

Viele Grüße

Alexander Wichmann

2020-02-09 16:20 UTC, HammerMaximilian commented
Hallo Herr Wichmann,

also, ich habe das Repository angepasst, die entsprechenden Binary-Ordner sind jetzt weg.
Wie das jetzt mit dem Pull-Request funktioniert weiß ich nicht. Er zeigt den neuen Commit in dem alten Pull-Request zumindest an, ich weiß nicht wie das ganze dann auf Ihrer Seite aussieht.
Ich kann auch keinen neuen erstellen, solange der letzte noch nicht geschlossen ist, kann ihn aber offenbar auch nicht selbst schließen 😃
Das geht wohl auch nur von Seiten des originalen Repos (also von Ihrer Seite aus).

Ich würde Sie bitten mal nachzuschauen, wie das Ganze jetzt von ihrer Seite aussieht und mir dann Bescheid zu geben, ob es so klappt und wie wir weiter machen falls nicht.

Viele Grüße
Maximilian Hammer

Von: Alexander Wichmann <notifications@github.com>
Gesendet: Donnerstag, 6. Februar 2020 09:36
An: MDE4CPP/MDE4CPP <MDE4CPP@noreply.github.com>
Cc: HammerMaximilian <maximilian.hammer@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [MDE4CPP/MDE4CPP] Development (#23)


Klar, bis nächste Woche kann der Spaß noch warten. Kein Problem.

Eine Korrektur von einem Pull-Request habe ich auch noch nicht gemacht. Im Zweifel ist die einfachste Lösung, den hier zu schließen und einen neuen zu erstellen.

Viele Grüße

Alexander Wichmann

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/MDE4CPP/MDE4CPP/pull/23?email_source=notifications&email_token=AOBXXT2CTMYWNKJEETKL2WDRBPDYTA5CNFSM4KPDMPA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK6LSVA#issuecomment-582793556>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOBXXTYCCFPNZ3ZN3FWQIOLRBPDYTANCNFSM4KPDMPAQ>.

2020-02-10 06:53 UTC, AlexanderWichmann approved these changes

2020-02-10 06:53 UTC, merged